// OOP stands for Object-Oriented Programming.


// object is an instance of a class.


//  In C++, an object is created from a class


// When the individual objects are created, they inherit all the variables and functions from the class.


// Procedural programming is about writing procedures 
// or functions that perform operations on the data, while object-oriented programming is about creating objects 
// that contain both data and functions.


// OOP is faster and easier to execute
// OOP provides a clear structure for the programs
// OOP helps to keep the C++ code DRY "Don't Repeat Yourself", and makes the code easier to maintain, modify and debug
// OOP makes it possible to create full reusable applications with less code and shorter development time


// Classes and objects are the two main aspects of object-oriented programming.